jwt:
  token:
    secret-key:
      access: 6rCA64KY64uk652866eI67CU7IKs # 가나다라마바사
      refresh: 7JWE7J6Q7LCo7Lm07YOA7YyM7ZWY # 아자차카타파하
    expired-time-ms:
      access: 1800 # 60 * 30
      refresh: 604800 # 60 * 60 * 24 * 7